### ISSUE TITLE
Any ideas how to create inner shadows for UILabel?

### ISSUE THREAD

**Issue by fatuhoku** [inamiy/YIInnerShadowView#13]
i.e. inner shadows for text? Can this be achieved through CoreText?

**Comment by inamiy** [comment]
This library is not for text inner-shadowing, but you can use CoreGraphics to draw on your own (not sure about CoreText).
These libraries might help you.

- https://github.com/nicklockwood/FXLabel
- https://github.com/MuscleRumble/THLabel
