### ISSUE TITLE
Can I hide the layer border?

### ISSUE THREAD

**Issue by matthewyan** [inamiy/YIInnerShadowView#9]
Hi

I set the layer's border width to 0, but it's still has a border.

my code:

```
YIInnerShadowLayer *innerShadowLayer = [YIInnerShadowLayer layer];
        innerShadowLayer.actions = [NSDictionary dictionaryWithObjectsAndKeys:
                                    [NSNull null], @"position",
                                    [NSNull null], @"bounds",
                                    [NSNull null], @"contents",
                                    [NSNull null], @"shadowColor",
                                    [NSNull null], @"shadowOpacity",
                                    [NSNull null], @"shadowOffset",
                                    [NSNull null], @"shadowRadius",
                                    nil];
        self.layer.borderWidth = 0;
        [self.layer addSublayer:innerShadowLayer];
        self.layer.masksToBounds = YES;
        innerShadowLayer.shadowRadius = 3.0f;
        innerShadowLayer.shadowColor = [UIColor blueColor].CGColor;
        innerShadowLayer.borderWidth = 0;
        innerShadowLayer.shadowOpacity = 0.7f;
        self.innerShadowLayer = innerShadowLayer;
```

how could i set property to hide the border? thanks!

**Comment by inamiy** [comment]
I guess you are setting `self.layer.borderWidth = 0;` instead of `self. innerShadowLayer.borderWidth = 0;`.

Does this solve your issue?

**Comment by matthewyan** [comment]
@inamiy  

self.layer.borderWidth = 0;
innerShadowLayer.borderWidth = 0;

Both of them are called, but the border is still exist.
（btw:my view is circle）

thanks~

**Comment by matthewyan** [comment]
@inamiy 

I figured it by another way:
make the innerlayer's bounds larger than view's layer, and set view's maskToBounds to YES

thanks

**Comment by inamiy** [comment]
@matthewyan 
Oh, I didn't notice you actually had 2 layers (please forget about previous comment).
Though I haven't tested for circle view, your solution sounds working.
Thanks for comment.

**Comment by fahrenkrug** [comment]
Hi! i also had the problem with the border and found a blog entry with code which helped me to solve it. check it out: http://armstrongnate.com/2015/03/18/uiview-inset-effect/
